### PR TITLE
SnippetStrings/ basic unit support

### PR DESCRIPTION
**Pull request by TheRealSyler**
changed `completionItem.insertText` from `item.body` to `new SnippetString(item.body)` so that if you use darken or other functions the carrot gets placed inside the parenthesis.
added unit autocompletion after certain keywords but not after numbers, that's on my todo list.
also added a snippet for `@keyframes` .

### CODE REVIEW

**Comment by robinbentley** [comment]
Thank you @TheRealSyler, I will take a look this week 👍

**Comment by minkir014** [comment]
Can you add support for the original html selectors such as `div` and `h1` etc? It would be a nice idea.

**Comment by TheRealSyler** [comment]
@minkir014 sure i can, but i don't want to spend the time doing it, its a pretty simple thing to add though so if you want it you should add it yourself, if you have experience with vscode extensions then it should only take around 2 hours max.

what you can do to add it to this extension is add a new file like `sassSchema` change the items to html selectors, then in the `sassAutocomplete` file add your file to the completions if the `currentWord` does not contain a word that you not want your completion to appear after, that should be it test it and if it works, send a pull request, last thing is if you do this please add a new option that disables html selectors from appearing in the completions, i almost never use them, i should have added that option for the units, but thats something to do another day.

**Comment by minkir014** [comment]
At least, add support for variables completion. Variables aren't completed even in the same file.

**Comment by TheRealSyler** [comment]
@minkir014 good idea will do it when i have the time to do it.

**Comment by minkir014** [comment]
OK. We want this feature as fast as possible.

**Comment by robinbentley** [comment]
@minkir014 As @TheRealSyler has mentioned you are more than welcome to contribute your own PR for features you would like to see. There is a bit more to variable completion than there is to static snippets and IMO it's not really worth the time to implement this for completion within single files. I also don't feel that HTML tag completion is all that valuable, with headings for example it would take more keystrokes to complete a `h1` than it would to type it. 

@TheRealSyler I've read through this and it all all looks good to me, I want to pull it down and use it before I accept the merge. I'm not working on any projects with sass atm so just need to revive an old one .

**Comment by minkir014** [comment]
@robinbentley I didn't mean that variables aren't only completed in the same file. They aren't completed neither in the same file nor across files. And about PRs I'll see what I can do.

**Comment by robinbentley** [comment]
@minkir014 I understand what you meant. I'm just saying that if there is going to be an implementation of variable completion then it's not really worth doing unless it's project wide. This really needs to consider performance, there has been one implementation already that worked well until working on bigger projects.

Happy to help with any PRs if they should come in

**Comment by TheRealSyler** [comment]
@robinbentley don't merge this, im working on a much better version which also supports variable completions and generates the unit completions so that they appear after you type a number.

**Comment by minkir014** [comment]
@TheRealSyler what do you mean that they appear after you type a unit??

**Comment by TheRealSyler** [comment]
@minkir014  was a typo i meant after you type a number.

**Comment by minkir014** [comment]
OK. I understood. Thanks.

**Pull request closed without merging**
